- name: copy tomcat
  get_url:
    url: "{{ url_tomcat }}"
    dest: '/tmp/'

- name: Create a directory for tomcat
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat distr
  become: yes
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_release }}.tar.gz"
    dest: /opt/tomcat
    remote_src: yes

- name: move tomcat in right place
  become: yes
  shell: | 
    mv /opt/tomcat/apache-tomcat-*/* /opt/tomcat 
    rm -rf /opt/tomcat/apache-tomcat-*
    rm -rf /tmp/apache-tomcat-{{ tomcat_release }}.tar.gz

- name: change file permission on tomcat folder
  become: yes
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    recurse: yes
    
- name: copy systemd tomcat file
  become: yes
  copy: 
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
  notify: "tomcat installed"