- name: get httpd version
  become: yes
  shell: /usr/sbin/httpd -version | grep "Server version" | awk '{print $3}' | sed 's/Apache\///'
  register: httpd_version
  listen: "httpd installed"

- name: create ansible folder
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
  listen: "httpd installed"

- name: save httpd version fact
  become: yes
  copy:
    content: |
      {
        "httpd_version": "{{ httpd_version.stdout }}"
      }
    dest: /etc/ansible/facts.d/httpd.fact
  listen: "httpd installed"