- name: create new user
  become: true
  user:
    name: devops
    comment: devops
    groups: wheel 
    append: yes 
    state: present

- name: Set authorized key to depovs user
  become: true
  authorized_key:
    user: devops
    state: present
    key: "{{ lookup('file', 'devopscert.pub') }}"

# add to sudo
- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'